### ISSUE TITLE
CRC cards

### ISSUE THREAD

**Issue by kostyayatsok** [igoroogle/pomodoros#2]
Добавили CRC карточки [https://github.com/igoroogle/pomodoros/blob/main/crc-cards.md](crc-cards.md) @nvamelichev

**Comment by nvamelichev** [comment]
* class changeTimer:
    * "recommendTime -- предлагает разбиение на 2 части оптимально (15/45)": Я правильно понимаю, что это просто удобный способ вызвать setTime() со стандартными настройками? Если так, то его можно из высокоуровневого дизайна убрать, это деталь реализации уже :-)
    * "**currentTime** -- выдает сколько времени осталось до конца периода" - название не соответствует содержанию. Я бы назвал **timeRemaining** ("оставшееся время")
    * Если помидорка+отдых закончились, что происходит с таймером? Он автоматически останавливается? Или начинает следующий цикл отсчёта? Или ещё что-то?
* Расскажите, как вы будете собирать статистику по разным категориям задач: Где-то в методах changeTimer будете указывать категорию? У вас будут отдельные таймеры под каждую категорию задач? Или ещё как-то?
* Может ли у вас работать несколько таймеров одновременно?

**Comment by kostyayatsok** [comment]
- "Я правильно понимаю, что это просто удобный способ вызвать setTime() со стандартными настройками?"  — предполагалось, что этот метод отвечает за установку таймера на основе собранной статистики. Так как это существенная часть нашей реализации, мы посчитали нужным указать этот метод в карточке.

- currentTime -> timeRemaining поправили.

- "что происходит с таймером" пользователю приходит запрос "продолжить работу?" и в зависимости от ответа таймер либо останавливается, либо начинается новый цикл. Опционально можно задать автоматическое продление (чтобы при отсутствие ответа на вопрос в течение заданного времени запускался новый цикл).

- "как вы будете собирать статистику  по разным категориям" - При запуске таймера пользователь может указать задачу которую он собирается выполнять.  Пока рабочий цикл не закончился статистика будет собираться для указанной категории.

- "Может ли у вас работать несколько таймеров одновременно?" - Мы не будем поддерживать несколько таймеров одновременно.  Одному человеку работать с несколькими помидорами одновременно не имеет смысла, а запускать таймеры из одной консоли нескольким людям кажется неудобным.

Также добавили UML диаграммы [dynamic-UML](https://github.com/igoroogle/pomodoros/blob/main/dynamic-UML.svg) и [static-UML](https://github.com/igoroogle/pomodoros/blob/main/static-UML.svg)

**Comment by nvamelichev** [comment]
По CRC-карточкам:
> предполагалось, что этот метод [**setTime**] отвечает за установку таймера на основе собранной статистики

Отлично, что подчеркнули этот момент в новой версии карточек ("setOptimalTime") :+1:

> в зависимости от ответа таймер либо останавливается, либо начинается новый цикл.

Окей, а таймер сам себя останавливает, или объект какого-то другого класса (getStat???) у него вызывает метод stop()? Сбрасывается ли прошедшее время в 0 при остановке таймера?

> При запуске таймера пользователь может указать задачу которую он собирается выполнять. Пока рабочий цикл не закончился статистика будет собираться для указанной категории.

То есть таймер взаимодействует с классом сбора статистики, верно?

> Мы не будем поддерживать несколько таймеров одновременно.

Ок. Проще внутренняя модель и проще пользователю :-)

**Моё заключение по CRC-карточкам: стало лучше, но пока ПО НИМ ОДНИМ мне не очень понятно, что происходит в системе, и хватит ли вам пары самых главных классов для реализации всей функциональности**.
Пожалуйста, добавьте больше деталей - скажем, укажите у классов Collaborators: кто взаимодействует с классом и для чего он это делает.

**Comment by nvamelichev** [comment]
По UML-диаграммам: нарисуйте ещё на диаграмме последовательности ситуацию, когда пользователь ставит таймер на паузу, а потом и вовсе останавливает (если остановить работающий таймер в вашей модели - возможно).

**Comment by kostyayatsok** [comment]
> Окей, а таймер сам себя останавливает, или объект какого-то другого класса (getStat???) у него вызывает метод stop()?

В случае если пользователь сообщил о том, что хочет закончить работу, то обработка этой команды происходит в классе getConsoleCommand, который дает соответствующую команду классу changeTimer.

> Сбрасывается ли прошедшее время в 0 при остановке таймера?

При остановке предполагается, что пользователь закончил работу, так что да, время сбрасывается. Для того чтобы время сохранилось следует использовать метод pause.

> То есть таймер взаимодействует с классом сбора статистики, верно?

Да, все верно.

**Comment by kostyayatsok** [comment]
@nvamelichev ответили на комментарии, добавили collaborators в карточки [crc-cards.md](https://github.com/igoroogle/pomodoros/blob/main/crc-cards.md) и сделали сценарий с постановкой на паузу и последующим завершением работы [dynamic-UML-pause.svg](https://github.com/igoroogle/pomodoros/blob/main/dynamic-UML-pause.svg).

**Comment by nvamelichev** [comment]
Улучшения вижу, **первая итерация дизайна принята &mdash; пишите код! :+1:**. Помните, первая демка уже в эту пятницу, 9 апреля.

----

Остались мелкие замечания по именам классов (getStat и т.п.). Согласно текущим конвенциям в мире Java:
* Имена Java-классов пишутся ВотТакВот (UpperCamelCase) (а у вас: lowerCamelCase).
* Имена вида "сделайВотЭто", типа "получиСтатистику" - не рекомендуются:
    1. Java - язык-"царство имён", где наибольший вес имеют "имена" (классы), а не "действия" (функции). В качестве имён Java-классов поэтому предпочитаются существительные, однозначно характеризующие класс (String - строка, CharSequence - последовательность символов, List - список, Invoice - накладная/инвойс, MapEntry - элемент отображения ключ-значение, ...). 
    2. Бывает так, что основная цель класса - выполнение какого-либо действия или категории действий. В таком случае рекомендуется сначала попробовать найти хорошее общее имя в соответствии с п. 1, например: Function (функция, выполняет преобразование одного значения в другое), UnaryOperator (унарный оператор, преобразует значение одного типа в значение того же самого типа) и т.п. Однако, если хорошее имя не находится - вполне нормально взять отглагольное существительное: Reader (читатель), Consumer (потребитель данных), ... или отглагольное прилагательное: Runnable, Callable ("запускаемый/вызываемый кусочек кода"), Throwable ("кидаемое" - что-то, что можно выкинуть с помощью `catch`) и т.д.

**Comment by nvamelichev** [comment]
@kostyayatsok @igoroogle ^^^
